// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgcfXwwlzpgLzWQJDt6INDHcEoT8v6Ppw',
    appId: '1:999815156607:web:155759a6796641b7eec04a',
    messagingSenderId: '999815156607',
    projectId: 'we-chat-52f23',
    authDomain: 'we-chat-52f23.firebaseapp.com',
    storageBucket: 'we-chat-52f23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPzoAI8UJd_vEJLZ6OOqhWm5UJeNluYl4',
    appId: '1:999815156607:android:03dd47842eb3c727eec04a',
    messagingSenderId: '999815156607',
    projectId: 'we-chat-52f23',
    storageBucket: 'we-chat-52f23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfTOLS8mq0tZvbnrZBcdJlHiIT733Pmnc',
    appId: '1:999815156607:ios:257fde39ee4520beeec04a',
    messagingSenderId: '999815156607',
    projectId: 'we-chat-52f23',
    storageBucket: 'we-chat-52f23.appspot.com',
    iosClientId: '999815156607-r3fa3oklqsiddkls9jee2edo2uve43h0.apps.googleusercontent.com',
    iosBundleId: 'com.example.wechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfTOLS8mq0tZvbnrZBcdJlHiIT733Pmnc',
    appId: '1:999815156607:ios:257fde39ee4520beeec04a',
    messagingSenderId: '999815156607',
    projectId: 'we-chat-52f23',
    storageBucket: 'we-chat-52f23.appspot.com',
    iosClientId: '999815156607-r3fa3oklqsiddkls9jee2edo2uve43h0.apps.googleusercontent.com',
    iosBundleId: 'com.example.wechat',
  );
}
